version: '3'
services:
  db:
    image: mysql:8.0
    container_name: db_test_mysql
    volumes:
      - db-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails db:create && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: web_test_mysql
    volumes:
      - .:/myapp
      - gem-data:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
# PC上にdb-volumeという名前でボリューム（データ領域）が作成される
# コンテナを作り直したとしてもPC上に残るようにするために設定
volumes:
  db-volume:
  gem-data: